# not using sudo
sudo: false

language: java

# setup the travis token
env:
  global:
    - secure: SX89cRLYoKCbkmzAiFdjif5QNGE4yAzeWP2pdevT9VO7KdX/6m7hpOnZJlkHCE+UoJlaKfd7SZPCKvnz+c8H2R2op+2v5Rz9FoCypHzqlE802XOsnHFusw9HLmjG5Zte42hi9/EkqtwSa2ecFhdsH49dOhR7oI0H4plXMBstt+g=

before_install:
 - cd ..
 - wget http://sourceforge.net/projects/dcm4che/files/dcm4chee-web/3.0.3/dcm4chee-web-3.0.3-src.zip
 - unzip -aa dcm4chee-web-3.0.3-src.zip
 - cd dcm4chee-web
 - mv ../dwv-dcm4chee-web .
 - patch pom.xml dwv-dcm4chee-web/resources/dcm4chee.patch

# update gh-pages if all good
after_success: 
 - chmod +x ./dwv-dcm4chee-web/resources/update-gh-pages.sh
 - ./dwv-dcm4chee-web/resources/update-gh-pages.sh

