# not using sudo
sudo: false

language: java

# setup the travis token
env:
  global:
    - secure: Gpihp9sulvCFSd1ZXxy4rSKGHxsb86IazFPsNJh2Hodo4pEmoDMOorbAgu6mlshiQO5dEpYZlY+nBWunCL1qPqJ+JRf3inGTTvjbNRSw0HSrMt1Mj1FtZJ41MrfkduSbijIsTv+Xi5vvr8iRFj/9uliorwT8hBbckpLaELa7bIs=

before_install:
 - mvn --version
 - cd ..
 - wget http://sourceforge.net/projects/dcm4che/files/dcm4chee-web/3.0.3/dcm4chee-web-3.0.3-src.zip
 - unzip -aa dcm4chee-web-3.0.3-src.zip
 - cd dcm4chee-web
 - mv ../dwv-dcm4chee-web .
 - patch pom.xml dwv-dcm4chee-web/resources/dcm4chee.patch

# update gh-pages if all good
after_success: 
 - chmod +x ./dwv-dcm4chee-web/resources/update-gh-pages.sh
 - ./dwv-dcm4chee-web/resources/update-gh-pages.sh

